
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnSumar;
	private global::Gtk.Button btnRestar;
	private global::Gtk.Button btnMultiplicar;
	private global::Gtk.Button btnDividir;
	private global::Gtk.Label lblNumero1;
	private global::Gtk.Label lblNumero2;
	private global::Gtk.Label lblNumero3;
	private global::Gtk.Entry resultado;
	private global::Gtk.Entry numero1;
	private global::Gtk.Entry numero2;
	private global::Gtk.Button btnLimpiar;
	private global::Gtk.Label label4;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSumar = new global::Gtk.Button ();
		this.btnSumar.CanFocus = true;
		this.btnSumar.Name = "btnSumar";
		this.btnSumar.UseUnderline = true;
		this.btnSumar.Label = global::Mono.Unix.Catalog.GetString ("SUMAR");
		this.fixed1.Add (this.btnSumar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSumar]));
		w1.X = 30;
		w1.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnRestar = new global::Gtk.Button ();
		this.btnRestar.CanFocus = true;
		this.btnRestar.Name = "btnRestar";
		this.btnRestar.UseUnderline = true;
		this.btnRestar.Label = global::Mono.Unix.Catalog.GetString ("RESTAR");
		this.fixed1.Add (this.btnRestar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnRestar]));
		w2.X = 104;
		w2.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMultiplicar = new global::Gtk.Button ();
		this.btnMultiplicar.CanFocus = true;
		this.btnMultiplicar.Name = "btnMultiplicar";
		this.btnMultiplicar.UseUnderline = true;
		this.btnMultiplicar.Label = global::Mono.Unix.Catalog.GetString ("MULTIPLICAR");
		this.fixed1.Add (this.btnMultiplicar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnMultiplicar]));
		w3.X = 179;
		w3.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDividir = new global::Gtk.Button ();
		this.btnDividir.CanFocus = true;
		this.btnDividir.Name = "btnDividir";
		this.btnDividir.UseUnderline = true;
		this.btnDividir.Label = global::Mono.Unix.Catalog.GetString ("DIVIDIR");
		this.fixed1.Add (this.btnDividir);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnDividir]));
		w4.X = 290;
		w4.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNumero1 = new global::Gtk.Label ();
		this.lblNumero1.Name = "lblNumero1";
		this.lblNumero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lblNumero1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNumero1]));
		w5.X = 27;
		w5.Y = 34;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNumero2 = new global::Gtk.Label ();
		this.lblNumero2.Name = "lblNumero2";
		this.lblNumero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lblNumero2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNumero2]));
		w6.X = 21;
		w6.Y = 83;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNumero3 = new global::Gtk.Label ();
		this.lblNumero3.Name = "lblNumero3";
		this.lblNumero3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblNumero3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNumero3]));
		w7.X = 21;
		w7.Y = 124;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Entry ();
		this.resultado.CanFocus = true;
		this.resultado.Name = "resultado";
		this.resultado.IsEditable = true;
		this.resultado.InvisibleChar = '●';
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w8.X = 131;
		w8.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero1 = new global::Gtk.Entry ();
		this.numero1.CanFocus = true;
		this.numero1.Name = "numero1";
		this.numero1.IsEditable = true;
		this.numero1.InvisibleChar = '●';
		this.fixed1.Add (this.numero1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero1]));
		w9.X = 132;
		w9.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero2 = new global::Gtk.Entry ();
		this.numero2.CanFocus = true;
		this.numero2.Name = "numero2";
		this.numero2.IsEditable = true;
		this.numero2.InvisibleChar = '●';
		this.fixed1.Add (this.numero2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero2]));
		w10.X = 131;
		w10.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLimpiar = new global::Gtk.Button ();
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.btnLimpiar);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnLimpiar]));
		w11.X = 305;
		w11.Y = 30;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Programado por : JOEL VALDIVIA");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w12.X = 119;
		w12.Y = 4;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 424;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSumar.Clicked += new global::System.EventHandler (this.OnBtnSumarClicked);
		this.btnRestar.Clicked += new global::System.EventHandler (this.OnBtnRestarClicked);
		this.btnMultiplicar.Clicked += new global::System.EventHandler (this.OnBtnMultiplicarClicked);
		this.btnDividir.Clicked += new global::System.EventHandler (this.OnBtnDividirClicked);
		this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
	}
}
